### ISSUE TITLE
docker run报错，麻烦看一下

### ISSUE THREAD

**Issue by nondevops** [luanlengli/wxwork-webhook#1]
![image](https://user-images.githubusercontent.com/12181410/66090442-fabc5a80-e5b5-11e9-8659-5d85a40cd509.png)

**Comment by luanlengli** [comment]
```bash
docker run -d \
           --restart=on-failure:5 \
           -p 5233:5233 \
           -w /usr/local/wxwork-webhook/
           IMAGE_NAME:TAG \
           python \
           app.py \
           --wxwork-webhook https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx \
           --listen 0.0.0.0 \
           --port 5233
```
这样试试

**Comment by nondevops** [comment]
@luanlengli 可以了，谢谢。另外可以将具体用法详细说明一下么？万分感谢

**Comment by luanlengli** [comment]
alertmanager 添加receivers配置和告警route的receiver
```yaml
receivers:
- name: "null"
- name: "wxwork-webhook"
  webhook_configs:
    - send_resolved: true
      url: "http://<YOUR wxwork-webhook IP address>:5233/webhook"
route:
  ...
  receiver: "wxwork-webhook"
  ...
```
